{{- if and (or $.Values.global.persistence.enabled $.Values.fourAllPortal.persistence.assets.enabled) .Values.backups.volumes.enabled -}}
  {{- range $volume := list "config" "assets" -}}
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: "{{ include "common.names.fullname" $ }}-{{ $volume }}"
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: volume
    app.kubernetes.io/part-of: backup
spec:
  repository:
    name: "{{ include "common.names.fullname" $ }}-{{ $volume }}"
  task:
    name: pvc-backup
  target:
    ref:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: "{{ include "common.names.fullname" $ }}-{{ $volume }}"
    exclude:
    - /stash-data/.health*
  schedule: "{{- $.Values.backups.volumes.schedule -}}"
  retentionPolicy:
    name: retention
    prune: {{ $.Values.backups.volumes.retention.prune }}
  {{- $.Values.backups.volumes.retention.policy | toYaml | nindent 4 }}
  runtimeSettings:
    container:
      securityContext: {{- $.Values.fourAllPortal.containerSecurityContext | toYaml | nindent 8 }}
    pod:
      securityContext: {{- $.Values.fourAllPortal.securityContext | toYaml | nindent 8 }}
---
{{ end -}}
  {{- end -}}
