{{- if and (or $.Values.global.persistence.enabled $.Values.fourAllPortal.persistence.assets.enabled) .Values.backups.volumes.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.secrets.name" (dict "existingSecret" (dict) "defaultNameSuffix" "backup" "context" $) }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.stable" $ | nindent 4 }}
    app.kubernetes.io/component: volume
    app.kubernetes.io/part-of: backup
stringData:
  RESTIC_PASSWORD: {{ .Values.backups.volumes.password | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.backups.target.s3.accessKey | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.backups.target.s3.secretKey | quote }}
{{- end -}}
