{{- if .Values.webdav.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: apikey-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  key: {{ include "4allportal.fourAllPortal.systemApiKey" . | b64enc }}
{{- end -}}