---
{{- if .Values.fourAllPortal.database.operator.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-databaseuser-secret
  namespace: {{ .Release.Namespace }}
stringData:
  user: {{ .Values.fourAllPortal.database.operator.user | quote }}
  password: {{ .Values.fourAllPortal.database.operator.password | quote }}
{{ end }}