{{- if .Values.fourAllPortal.database.operator.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-databaseuser-secret
  namespace: {{ .Release.Namespace }}
data:
  password: {{ required "You must set a user password when using the operator." .Values.fourAllPortal.database.operator.password | b64enc }}
  user: {{ required "You must set a database user when using the operator." .Values.fourAllPortal.database.operator.user | b64enc }}
  database: {{ required "You must set a database name when using the operator." .Values.fourAllPortal.database.operator.databaseName | b64enc }}
---
apiVersion: com.fourallportal.credentialsoperator/v1beta1
kind: DatabaseUser
metadata:
  name: {{ .Release.Name }}-databaseuser
  namespace: {{ .Release.Namespace }}
spec:
  database: {{ .Values.fourAllPortal.database.operator.databaseRef }}
  databaseName: {{ .Values.fourAllPortal.database.operator.databaseName }}
  secretName: {{ .Release.Name }}-databaseuser-secret
{{ end }}