---
{{- if .Values.fourAllPortal.database.operator.enabled -}}
apiVersion: com.fourallportal.credentialsoperator/v1beta1
kind: DatabaseUser
metadata:
  name: {{ .Release.Name }}-databaseuser
  namespace: {{ .Release.Namespace }}
spec:
  database: {{ .Values.fourAllPortal.database.operator.databaseRef }}
  databaseName: {{ .Values.fourAllPortal.database.operator.databaseName }}
  secretName: {{ .Release.Name }}-databaseuser-secret
{{ end }}