{{- if .Values.fourAllPortal.database.operator.enabled -}}
  {{- $externalSecret := .Values.fourAllPortal.database.operator.secretName -}}
  {{- if empty $externalSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-databaseuser-secret
  namespace: {{ .Release.Namespace }}
  labels:
    database-operator.fourallportal.com/input-secret: "true"
stringData:
  user: {{ .Values.fourAllPortal.database.operator.user | default .Release.Name | quote }}
  database: {{ .Values.fourAllPortal.database.operator.databaseName | default (printf "%s-4allportal" .Release.Name) | quote }}
    {{- if not (empty .Values.fourAllPortal.database.operator.password) }}
  password: {{ .Values.fourAllPortal.database.operator.password | quote }}
    {{- end }}
  {{- end }}
---
apiVersion: com.fourallportal.credentialsoperator/v1beta1
kind: DatabaseUser
metadata:
  name: {{ .Release.Name }}-databaseuser
  namespace: {{ .Release.Namespace }}
spec:
  database: {{ .Values.fourAllPortal.database.operator.databaseRef | quote }}
    {{- if $externalSecret }}
  secretName: {{ $externalSecret }}
      {{- if not (empty .Values.fourAllPortal.database.operator.databaseName) }}
  databaseName: {{ .Values.fourAllPortal.database.operator.databaseName | quote }}
      {{- end }}
    {{- else }}
  databaseName: {{ .Values.fourAllPortal.database.operator.databaseName | default (printf "%s-4allportal" .Release.Name) | quote }}
  secretName: {{ .Release.Name }}-databaseuser-secret
    {{- end }}
{{- end }}
