{{- if .Values.fourAllPortal.database.operator.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-databaseuser-secret
  namespace: {{ .Release.Namespace }}
stringData:
  user: {{ .Values.fourAllPortal.database.operator.user | quote }}
  password: {{ .Values.fourAllPortal.database.operator.password | quote }}
---
apiVersion: com.fourallportal.credentialsoperator/v1beta1
kind: DatabaseUser
metadata:
  name: {{ .Release.Name }}-databaseuser
  namespace: {{ .Release.Namespace }}
spec:
  database: {{ .Values.fourAllPortal.database.operator.databaseRef }}
  databaseName: {{ .Values.fourAllPortal.database.operator.databaseName }}
  {{- if .Values.fourAllPortal.database.operator.secretName -}}
  secretName: {{- .Values.fourAllPortal.database.operator.secretName }}
  {{- else -}}
  secretName: {{ .Release.Name }}-databaseuser-secret
  {{- end -}}
{{ end }}