{{- if and .Values.fourAllPortal.ingress.enabled .Values.fourAllPortal.ingress.endpointMonitor.enabled (eq (include "4allportal.isHa" .) "true") not eq .Values.fourAllPortal.replicas  0 }}
apiVersion: endpointmonitor.stakater.com/v1alpha1
kind: EndpointMonitor
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
spec:
  forceHttps: true
  urlFrom:
    ingressRef:
      name: {{ include "common.names.fullname" . }}
  {{- if (omit .Values.fourAllPortal.ingress.endpointMonitor "enabled") }}
  {{- omit .Values.fourAllPortal.ingress.endpointMonitor "enabled" | toYaml | nindent 2}}
  {{- end }}
  {{- end }}
