{{- $ingresses := dict "@" .Values.fourAllPortal.ingress -}}
{{ range $name, $ingress := .Values.fourAllPortal.ingress.additionalHosts -}}
  {{- $ingresses = set $ingresses $name $ingress -}}
{{- end -}}

{{- range $name, $ingress := $ingresses }}
  {{ if $ingress.existingCertificate }}
    {{- if and $ingress.existingCertificate.cert $ingress.existingCertificate.key (not $ingress.existingCertificate.name) -}}
    {{- $secretName := eq $name "@" | ternary "" (printf "-%s" $name) -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "common.secrets.name" (dict "existingSecret" $ingress.existingCertificate "defaultNameSuffix" (printf "%s%s" "custom-certificate" $secretName) "context" $) }}
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "common.labels.stable" $ | nindent 4 }}
data:
  tls.crt: {{ $ingress.existingCertificate.cert | b64enc | quote }}
  tls.key: {{ $ingress.existingCertificate.key | b64enc | quote }}
---
    {{- end }}
  {{- end }}
{{- end }}
