{{- if .Values.fourAllPortal.middleware.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: internal-access
  namespace: {{ $.Release.Namespace }}
spec:
  ipWhiteList:
    sourceRange:
      # List of IPs to whitelist {{ .Values.fourAllPortal.middleware.ipList | toYaml | nindent 6 }}
    {{ if .Values.fourAllPortal.ingress.endpointMonitor.enabled }}
      # UptimeRobot Main Servers (USA only) {{- include "middleware.utr.main" . | nindent 6 }}

      # UptimeRobot Secondary Servers (World-Wide) {{ include "middleware.utr.secondary" . | nindent 6 }}
    {{- end }}
{{- end }}
