{{- if and (.Values.fourAllPortal.ipWhitelist.enabled) (gt (.Values.fourAllPortal.ipWhitelist.ipList | len) 0) }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $.Release.Name }}-internal-access
  namespace: {{ $.Release.Namespace }}
spec:
  ipWhiteList:
    sourceRange:
      # List of IPs to whitelist {{- .Values.fourAllPortal.ipWhitelist.ipList | toYaml | nindent 6 }}
    {{ if .Values.fourAllPortal.ingress.endpointMonitor.enabled }}
      # UptimeRobot Main Servers (USA only) {{- include "ipWhitelist.utr.main" . | nindent 6 }}

      # UptimeRobot Secondary Servers (World-Wide) {{- include "ipWhitelist.utr.secondary" . | nindent 6 }}
    {{- end }}
{{- end }}
