{{- if false }}
apiVersion: rbac.authorization.k8s.io/v1
  {{- else }}
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
  {{- end }}
kind: RoleBinding
metadata:
  name: "{{ include "common.names.fullname" . }}-backend"
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: "{{ include "common.names.fullname" . }}-backend"
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ include "common.names.fullname" . }}-backend-restart"
