{{- if or (eq .Values.fourAllPortal.general.admin.secret.key "") (eq .Values.fourAllPortal.general.admin.secret.name "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.secrets.name" (dict "existingSecret" (dict) "defaultNameSuffix" "general" "context" $) }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.stable" $ | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ required "You must provide a password for the administrator account" .Values.fourAllPortal.general.admin.password | quote }}
{{- end -}}
  {{- if and .Values.fourAllPortal.mail.enabled .Values.fourAllPortal.mail.useAuthentication (or (eq .Values.fourAllPortal.mail.secret.name "") (eq .Values.fourAllPortal.mail.secret.key "")) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.secrets.name" (dict "existingSecret" (dict) "defaultNameSuffix" "mail" "context" $) }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.stable" $ | nindent 4 }}
type: Opaque
stringData:
  mail-password: {{ required "You must provide a mail password, when enabling mail. If this is not a mistake, set `useAuthentication: false`" .Values.fourAllPortal.mail.password | quote }}
  {{ end }}
  {{ if not .Values.fourAllPortal.database.existing.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.secrets.name" (dict "existingSecret" .Values.fourAllPortal.database.existing.existingSecret "defaultNameSuffix" "database" "context" $) }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.stable" $ | nindent 4 }}
type: Opaque
stringData:
  password: {{ include "4allportal.fourallportal.database.password" . | quote }}
{{- end -}}
