apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "common.names.fullname" . }}-backend"
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
automountServiceAccountToken: true
  {{- include "4allportal.imagePullSecrets" . | nindent 0 }}
secrets:
  - name: {{ include "common.secrets.name" (dict "existingSecret" (dict) "defaultNameSuffix" "general" "context" $) }}
  {{- if and .Values.fourAllPortal.mail.enabled .Values.fourAllPortal.mail.useAuthentication }}
  - name: {{ include "common.secrets.name" (dict "existingSecret" (dict) "defaultNameSuffix" "mail" "context" $) }}
  {{- end }}
  - name: {{ include "common.secrets.name" (dict "existingSecret" .Values.fourAllPortal.database.existing.existingSecret "defaultNameSuffix" "database" "context" $) }}
