{{- if eq (include "common.networkPolicy.type" .) "cilium" }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
spec:
  endpointSelector:
    matchLabels: {{- include "common.labels.matchLabels" $ | nindent 6 }}
  ingress:
    - fromEndpoints:
        - matchLabels: {{- include "common.tplvalues.render" (dict "value" (include "common.dict.filterEmptyValues" .Values.global.networkPolicy.applicationLabels) "context" $) | nindent 12 }}
      toPorts:
        - ports:
            - port: "3306"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels: {{- include "common.labels.matchLabels" (dict "Release" $.Release "Chart" (dict "Name" "mariadb") "Values" $.Values.mariadb) | nindent 12 }}
            io.kubernetes.pod.namespace: {{ .Release.Namespace }}
      toPorts:
        - ports:
            - port: "3306"
              protocol: TCP
    - toEndpoints:
        - matchLabels: {{- include "common.tplvalues.render" (dict "value" (include "common.dict.filterEmptyValues" .Values.global.networkPolicy.dnsLabels) "context" $) | nindent 12 }}
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
  {{- end }}
