apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-configuration
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.stable" $ | nindent 4 }}
data:
  maxscale.cnf: |-
    [maxscale]
    threads= {{- include "maxscale.cnf.cpu.limit" . }}
    query_classifier_cache_size= {{- include "maxscale.cnf.memory.limit" . }}
    substitute_variables=true
    piddir=/var/cache/maxscale
    persistdir=/var/cache/maxscale
    datadir=/var/cache/maxscale
    admin_gui=false
  mariadb-galera.cnf: |-
    {{- $servers := list -}}
    {{- $fullName := include "common.names.dependency.fullname" (dict "chartName" "mariadb" "chartValues" $.Values.mariadb "context" $) -}}
    {{- range $INDEX := until (.Values.mariadb.replicaCount | int) -}}
    {{- $server := printf "server-%d" $INDEX -}}
    {{- $servers = append $servers $server }}

    [{{ $server }}]
    type=server
    address={{- printf "%s-%d.%s-headless.%s.svc.%s" $fullName $INDEX $fullName ($.Release.Namespace) $.Values.mariadb.clusterDomain }}
    port=3306
    protocol=MariaDBBackend
    {{- end }}

    # Monitor for the servers
    # This will keep MaxScale aware of the state of the servers.

    [MariaDB-Monitor]
    type=monitor
    module=galeramon
    servers={{ $servers | join "," }}
    user=root
    password=$MAXSCALE_PASSWORD
    backend_connect_timeout=3s
    backend_write_timeout=3s
    backend_read_timeout=3s
    disable_master_failback=false
    disable_master_role_setting=false

    # Service definitions
    # Service Definition for a read-only service and a read/write splitting service.

    [Read-Write-Service]
    type=service
    router=readwritesplit
    master_failure_mode=fail_on_write
    servers={{ $servers | join "," }}
    user=root
    password=$MAXSCALE_PASSWORD
    enable_root_user=true

    # Listener definitions for the services
    # Listeners represent the ports the services will listen on.

    [Read-Write-Listener]
    type=listener
    service=Read-Write-Service
    protocol=MariaDBClient
    port=3306
