apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.secrets.name" (dict "existingSecret" (dict) "defaultNameSuffix" "" "context" $) }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.stable" $ | nindent 4 }}
type: Opaque
stringData:
  root-password: {{ required "You must provide a root password for the bundled MariaDB deployment" .Values.mariadb.rootUser.password | quote }}
