{{- if .Values.dreiDRenderer.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ include "common.names.fullname" . }}-3d-renderer"
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: 3d-renderer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ include "common.names.fullname" . }}-3d-renderer"
  minReplicas: {{ .Values.dreiDRenderer.hpa.minReplicas }}
  maxReplicas: {{ .Values.dreiDRenderer.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: 90
  {{- end }}
