{{- if .Values.backups.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.secrets.name" (dict "existingSecret" (dict) "defaultNameSuffix" "mysql-backup" "context" $) }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: mysql
    app.kubernetes.io/part-of: backup
stringData:
  s3cfg: |-
    host_base = {{ .Values.backups.target.s3.endpoint }}
    host_bucket = {{ .Values.backups.target.s3.endpoint }}
    bucket_location = bucket_location
    use_https = False
    access_key = {{ .Values.backups.target.s3.accessKey }}
    secret_key = {{ .Values.backups.target.s3.secretKey }}
  {{- end -}}
