{{- if .Values.rbac.create }}
  {{ range $name := .Values.rbac.users }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    user: {{ $name }}
secrets:
  - name: {{ $name }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ $name }}
---
{{- end -}}
{{- end -}}
