{{- if .Values.monitoring.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: high-storage-usage
  namespace: monitoring
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  groups:
    - name: high-storage-usage
      rules:
        - alert: HighStorageUsage
          annotations:
            description: The storage usage on node {{ "{{ $labels.node }}" }} is currently {{ "{{ $value * 100 }}" }}%, which is above the threshold of 80%. 
            summary: Over 80 % of storage usage on {{ "{{ $labels.node }}" }} 
          expr: |-
            (kubelet_volume_stats_used_bytes {job="kubelet",metrics_path="/metrics",namespace=~".*"} / kubelet_volume_stats_capacity_bytes{job="kubelet",metrics_path="/metrics",namespace=~".*"}) >= 0.8
          for: 24h
          labels:
            severity: critical
  {{- end }}
