{{- if .Values.samba.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "common.names.fullname" $ }}-samba"
  namespace: {{ .Release.Namespace }}
data:
  config.json: |-
    {
      "samba-container-config": "v0",
      "configs": {
        "mountconf": {
          "shares": [
            "assets", "data"
            {{- range $mount, $i := .Values.samba.mounts -}},
            {{- regexReplaceAll "\\W+" (regexReplaceAll "^/(.*)" $mount "$1") "_" | quote }}
            {{- end }}
          ],
          "globals": [
            "globals"
          ],
          "instance_name": "assets",
          "permissions": {
            "method": "initialize-share-perms",
            "status_xattr": "user.share-perms-status",
            "mode": "0777"
          }
        }
      },
      "shares": {
        {{- range $mount, $perms := .Values.samba.mounts -}}
        {{- regexReplaceAll "\\W+" (regexReplaceAll "^/(.*)" $mount "$1") "_" | quote | nindent 8 }}: {
          "options": {
            "force user": "4allportal",
            "browseable": "yes",
            "path": "/mnt{{- $mount }}",
            "read only": "no"
            {{- if $perms.users -}}
            ,
            "valid users": {{ $perms.users | join "," | quote }}
            {{- end }}
          }
        },
        {{- end }}
        "assets": {
          "options": {
            "force user": "4allportal",
            "browseable": "yes",
            "path": "/mnt/assets",
            "read only": "no"
          }
        },
        "data": {
          "options": {
            "force user": "4allportal",
            "browseable": "yes",
            "path": "/mnt/data",
            "read only": "no"
          }
        }
      },
      "globals": {
        "globals": {
          "options": {
            "server min protocol": "SMB3",
            "server smb encrypt": "required",
            "client smb encrypt": "required",
            "client min protocol": "SMB3",
            "disable spoolss": "yes",
            "dos charset": "ascii",
            "fileid:algorithm": "fsid",
            "load printers": "no",
            "printcap name": "/dev/null",
            "printing": "bsd",
            "smb ports": "445",
            "vfs objects": "fileid"
          }
        }
      }
    }
{{- end -}}
