{{- if .Values.samba.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "common.names.fullname" $ }}-samba"
  namespace: {{ .Release.Namespace }}
data:
  config.json: |-
    {
      "samba-container-config": "v0",
      "configs": {
        "mountconf": {
          "shares": [
            {{- $keys := .Values.samba.mounts | keys | sortAlpha }}
            {{- $lastIndex := sub (len $keys) 1 }}
            {{- range $i, $k := $keys }}
              {{ regexReplaceAll "\\W+" (regexReplaceAll "^/(.*)" $k "$1") "_" | quote }}
              {{- if lt $i $lastIndex }},{{ end }}
            {{- end }}
          ],
          "globals": [
            "globals"
          ],
          "instance_name": "assets",
          "permissions": {
            "method": "initialize-share-perms",
            "status_xattr": "user.share-perms-status",
            "mode": "0777"
          }
        }
      },
      "shares": {
        {{- $keys := .Values.samba.mounts | keys | sortAlpha }}
        {{- range $i, $k := $keys }}
        {{- $perms := index $.Values.samba.mounts $k }}
        {{- $shareName := regexReplaceAll "\\W+" (regexReplaceAll "^/(.*)" $k "$1") "_" }}
        {{ $shareName | quote }}: {
          "options": {
            "force user": "4allportal",
            "browseable": "yes",
            "path": "/mnt{{ $k }}",
            "read only": "no",
            "valid users": {{ append $perms.users "admin" | uniq | join "," | quote }}
          }
        }{{- if lt (add $i 1) (len $keys) }},{{ end }}
        {{- end }}
      },
      "globals": {
        "globals": {
          "options": {
            "server min protocol": "SMB3",
            "server smb encrypt": "required",
            "client smb encrypt": "required",
            "client min protocol": "SMB3",
            "disable spoolss": "yes",
            "dos charset": "ascii",
            "fileid:algorithm": "fsid",
            "load printers": "no",
            "printcap name": "/dev/null",
            "printing": "bsd",
            "smb ports": "445",
            "vfs objects": "fileid"
          }
        }
      }
    }
{{- end }}
