{{- if $.Values.samba.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "common.secrets.name" (dict "existingSecret" (dict) "defaultNameSuffix" "samba" "context" $) }}
  namespace: {{ .Release.Namespace }}
stringData:
  users: |-
    {
      "samba-container-config": "v0",
      "users": {
        "all_entries": [
          {
            "name": "admin",
            "password": "CjXYjwF7kqLaf2NbAqTSdAUqS"
          }
        ]
      }
    }
{{- end }}
