{{- if .Values.samba.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "common.secrets.name" (dict "existingSecret" (dict) "defaultNameSuffix" "samba" "context" $) }}
  namespace: {{ .Release.Namespace }}
stringData:
  users: |-
    {
      "samba-container-config": "v0",
      "users": {
        "all_entries": [
          {{- with .Values.samba.users }}
          {{- range $k, $v := . }}
          {
            "name": {{ $k | quote }},
            "password": {{ $v | quote }}
          },
          {{- end }}
          {{- end }}
          {
            "name": "admin",
            "password": {{ .Values.samba.adminPassword | quote }}
          }
        ]
      }
    }
{{- end }}
