{{- if .Values.samba.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "common.names.fullname" $ }}-samba"
  namespace: {{ .Release.Namespace }}
  labels:
    samba-service: enabled
  {{- if .Values.fourAllPortal.ingress.enabled }}
    hostname: {{ .Values.fourAllPortal.ingress.host }}
  {{- end }}
spec:
  ports:
    - name: smb
      port: 445
      targetPort: smb
  selector: {{- include "common.labels.matchLabels" $ | nindent 4 }}
    app.kubernetes.io/component: samba
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "common.names.fullname" $ }}-samba-server"
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.samba.service.prefix | default "portals" }}-samba-server.{{ .Values.samba.service.namespace | default "portals" }}.svc.cluster.local
  ports:
    - name: ws
      port: 80
      targetPort: ws
{{- end }}
