{{- if and .Values.speedtest.enabled (lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "middlewares.traefik.io") }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "common.names.fullname" $ }}-speedtest-no-compression
  namespace: ingress
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
spec:
  headers:
    customRequestHeaders:
      Accept-Encoding: identity
    customResponseHeaders:
      Content-Encoding: identity
{{- end -}}
