apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  annotations:
    helm.sh/resource-policy: keep
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: ingress
