{{- if .Values.monitoring.deadMansSwitch.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: dead-mans-switch-unregister
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: dead-mans-switch
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: unregister
          image: {{ include "base-cluster.kubectl.image" . }}
          {{- if .Values.global.kubectl.image.repository | contains "@" }}
          imagePullPolicy: IfNotPresent
          {{- else }}
          imagePullPolicy: Always
          {{- end }}
          command:
            - bash
            - -ex
            - -c
            - |
              set -o pipefail

              apiKey={{- .Values.monitoring.deadMansSwitch.apiKey | quote }}
              function deleteCheck() {
                local checkName="$1"
                local existingChecks
                existingChecks="$(curl --silent --fail --retry 5 --max-time 30 --header "X-Api-Key: $apiKey" https://healthchecks.io/api/v1/checks/)"
                local existingCheckUUID
                existingCheckUUID="$(jq -r ".checks[] | select(.name == \"$checkName\") | .ping_url | split(\"/\") | last" <<< "$existingChecks")"

                if curl --silent --fail --retry 5 --max-time 30 --header "X-Api-Key: $apiKey" https://healthchecks.io/api/v1/checks/$existingCheckUUID > /dev/null; then
                  curl --silent --fail --retry 5 --max-time 30 --header "X-Api-Key: $apiKey" https://healthchecks.io/api/v1/checks/$existingCheckUUID --request DELETE
                fi
              }

              checkName={{- printf "k8s-cluster-%s-%s" (.Values.global.baseDomain | replace "." "-") .Values.global.clusterName | quote }}
              {{- if .Values.monitoring.prometheus.enabled }}
              deleteCheck "$checkName-monitoring"
              {{- end }}
              deleteCheck "$checkName-scheduling"
{{- end }}
