{{- if .Values.sealedsecrets.enabled -}}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: {{ .Release.Namespace }}
spec:
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      version: ">=1.15.0-0"
  interval: 1h0m0s
  releaseName: sealed-secrets-controller
  targetNamespace: {{ .Release.Namespace }}
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    image:
      repository: bitnamilegacy/sealed-secrets-controller
    {{- .Values.sealedsecrets.values | toYaml | nindent 8 }}
{{- end -}}