{
 "title": "4ALLPORTAL Alerts",
 "panels": [
  {
   "title": "ERROR Log Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(logback_events_total{level=~\"error\",service=~\".*4allportal-backend\"}[5m])) by (service,level)",
     "legendFormat": "{{level}}: {{service}}"
    }
   ]
  },
  {
   "title": "WARN Log Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(logback_events_total{level=~\"warn\",service=~\".*4allportal-backend\"}[5m])) by (service,level)",
     "legendFormat": "{{level}}: {{service}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{container!~\"^$|POD\",pod=~\".*4allportal.*\"}) by (pod, container) / sum(container_spec_memory_limit_bytes{container!~\"^$|POD\",pod=~\".*4allportal.*\"} > 0) by (pod, container))",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  }
 ]
}