{
 "title": "4ALLPORTAL Metrics",
 "templating": {
  "list": [
   {
    "name": "4ALLPORTAL",
    "query": {
     "query": "label_values(kube_deployment_labels{label_app_kubernetes_io_name=\"4allportal\",label_app_kubernetes_io_component=\"backend\"},label_app_kubernetes_io_instance)"
    }
   },
   {
    "name": "4ALLPORTAL_DB",
    "query": {
     "query": "label_values(kube_pod_labels{label_app_kubernetes_io_name=\"mariadb\",label_app_kubernetes_io_instance=\"$4ALLPORTAL\"},label_statefulset_kubernetes_io_pod_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "4ALLPORTAL Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Assets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(m_4allportal_number_of_assets{service=\"$4ALLPORTAL-4allportal-backend\"})",
     "legendFormat": "Number of assets"
    },
    {
     "expr": "avg(m_4allportal_number_of_deleted_assets{service=\"$4ALLPORTAL-4allportal-backend\"})",
     "legendFormat": "Deleted Assets"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(m_4allportal_active_sessions{service=\"$4ALLPORTAL-4allportal-backend\"})",
     "legendFormat": "Active Sessions"
    },
    {
     "expr": "max(m_4allportal_active_user{service=\"$4ALLPORTAL-4allportal-backend\"})",
     "legendFormat": "Unique Users"
    }
   ]
  },
  {
   "title": "Filetype Categories",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(m_4allportal_filetype{service=\"$4ALLPORTAL-4allportal-backend\"}) by (FileType,FileTypeCat)) by (FileTypeCat)",
     "legendFormat": "{{FileTypeCat}}"
    }
   ]
  },
  {
   "title": "Uploads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Uploads / Day" }
   ],
   "targets": [
    {
     "expr": "avg(m_4allportal_number_of_uploads{service=\"$4ALLPORTAL-4allportal-backend\"})",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "max(rate(m_4allportal_requests{service=\"$4ALLPORTAL-4allportal-backend\"}[4h]) != 0) by(Status)",
     "legendFormat": "{{Status}}"
    }
   ]
  },
  {
   "title": "Filetypes",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(m_4allportal_filetype{service=\"$4ALLPORTAL-4allportal-backend\"}) by (FileType)",
     "legendFormat": "{{FileType}}"
    }
   ]
  },
  {
   "title": "Max HTTP response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(http_server_requests_duration_seconds_max{pod=~\"$4ALLPORTAL-4allportal-backend.*\"}) by (method,pod)",
     "legendFormat": "{{pod}}/{{method}}"
    }
   ]
  },
  {
   "title": "Max database response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "m_4allportal_database_duration_seconds_max{pod=~\"$4ALLPORTAL-4allportal-backend.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(tomcat_global_sent_bytes_total{pod=~\"$4ALLPORTAL-4allportal-backend.*\"}[5m])",
     "legendFormat": "Egress {{pod}}"
    },
    {
     "expr": "rate(tomcat_global_received_bytes_total{pod=~\"$4ALLPORTAL-4allportal-backend.*\"}[5m])",
     "legendFormat": "Ingress {{pod}}"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(jvm_threads_peak_threads{pod=~\"$4ALLPORTAL-4allportal-backend.*\"})",
     "legendFormat": "Peak Threads"
    },
    {
     "expr": "max(jvm_threads_states_threads{pod=~\"$4ALLPORTAL-4allportal-backend.*\"}) by (state)",
     "legendFormat": "Threads in state: {{state}}"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_duration_seconds_count{pod=~\"$4ALLPORTAL-4allportal-backend.*\"}[1m])) by (status, pod)",
     "legendFormat": "{{pod}}: {{status}}"
    }
   ]
  },
  {
   "title": "Log Events (warn|error)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(logback_events_total{pod=~\"$4ALLPORTAL-4allportal-backend.*\",level=~\"error|warn\"}[5m])) by (level,pod)",
     "legendFormat": "{{level}}: {{pod}}"
    }
   ]
  },
  { "title": "Pod Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$4ALLPORTAL-4allportal-backend.*\",container!~\"^$|POD\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$4ALLPORTAL-4allportal-backend.*\",container!~\"^$|POD\"} / container_spec_memory_limit_bytes{pod=~\"$4ALLPORTAL-4allportal-backend.*\",container!~\"^$|POD\"}) by (pod)",
     "legendFormat": "% {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"$4ALLPORTAL-4allportal-backend.*\",container!~\"^$|POD\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{pod=~\"$4ALLPORTAL-4allportal-backend.*\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{pod=~\"$4ALLPORTAL-4allportal-backend.*\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Open files",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{pod=~\"$4ALLPORTAL-4allportal-backend.*\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "process_files_open_files{pod=~\"$4ALLPORTAL-4allportal-backend.*\"} / process_files_max_files{pod=~\"$4ALLPORTAL-4allportal-backend.*\"}",
     "legendFormat": "% {{pod}}"
    }
   ]
  },
  { "title": "Storage Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Asset Volume Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(topk(1,kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"$4ALLPORTAL-4allportal-assets\"})) - sum(topk(1,kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"$4ALLPORTAL-4allportal-assets\"}))",
     "legendFormat": "Used Space"
    },
    {
     "expr": "sum(topk(1,kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"$4ALLPORTAL-4allportal-assets\"}))",
     "legendFormat": "Free Space"
    },
    {
     "expr": "sum(topk(1,kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"$4ALLPORTAL-4allportal-assets\"}))",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Asset Volume Space Usage %",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((topk(1,kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"$4ALLPORTAL-4allportal-assets\"}) - topk(1,kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"$4ALLPORTAL-4allportal-assets\"})) / topk(1,kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"$4ALLPORTAL-4allportal-assets\"}))"
    }
   ]
  },
  {
   "title": "Config Volume Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(topk(1,kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"$4ALLPORTAL-4allportal-config\"})) - sum(topk(1,kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"$4ALLPORTAL-4allportal-config\"}))",
     "legendFormat": "Used Space"
    },
    {
     "expr": "sum(topk(1,kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"$4ALLPORTAL-4allportal-config\"}))",
     "legendFormat": "Free Space"
    },
    {
     "expr": "sum(topk(1,kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"$4ALLPORTAL-4allportal-config\"}))",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Config Volume Space Usage %",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((topk(1,kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"$4ALLPORTAL-4allportal-config\"}) - topk(1,kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"$4ALLPORTAL-4allportal-config\"})) / topk(1,kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"$4ALLPORTAL-4allportal-config\"}))"
    }
   ]
  },
  {
   "title": "Database Metrics $4ALLPORTAL_DB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "repeat": "4ALLPORTAL_DB"
  },
  {
   "title": "QPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries{pod=\"$4ALLPORTAL_DB\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_buffer_pool_size{pod=\"$4ALLPORTAL_DB\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", persistentvolumeclaim=\"data-$4ALLPORTAL_DB\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", persistentvolumeclaim=\"data-$4ALLPORTAL_DB\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", persistentvolumeclaim=\"data-$4ALLPORTAL_DB\"})\n* 100)\n"
    }
   ]
  },
  {
   "title": "Memory Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mysql_global_status_innodb_page_size{pod=\"$4ALLPORTAL_DB\"} * on (instance) mysql_global_status_buffer_pool_pages{pod=\"$4ALLPORTAL_DB\",state=\"data\"}",
     "legendFormat": "InnoDB Buffer Pool Data"
    },
    {
     "expr": "mysql_global_variables_innodb_log_buffer_size{pod=\"$4ALLPORTAL_DB\"}",
     "legendFormat": "InnoDB Log Buffer Size"
    },
    {
     "expr": "mysql_global_variables_key_buffer_size{pod=\"$4ALLPORTAL_DB\"}",
     "legendFormat": "Key Buffer Size"
    },
    {
     "expr": "mysql_global_variables_query_cache_size{pod=\"$4ALLPORTAL_DB\"}",
     "legendFormat": "Query Cache Size"
    },
    {
     "expr": "kube_pod_container_resource_limits{pod=\"$4ALLPORTAL_DB\",container=\"mariadb-galera\",resource=\"memory\"}",
     "legendFormat": "_Total Memory"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "targets": [
    {
     "expr": "irate(mysql_global_status_slow_queries{pod=\"$4ALLPORTAL_DB\"}[5m])",
     "legendFormat": "Slow Queries"
    }
   ]
  },
  {
   "title": "Select Types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_select_full_join{pod=\"$4ALLPORTAL_DB\"}[5m])",
     "legendFormat": "Select Full Join"
    },
    {
     "expr": "irate(mysql_global_status_select_full_range_join{pod=\"$4ALLPORTAL_DB\"}[5m])",
     "legendFormat": "Select Full Range Join"
    },
    {
     "expr": "irate(mysql_global_status_select_range{pod=\"$4ALLPORTAL_DB\"}[5m])",
     "legendFormat": "Select Range"
    },
    {
     "expr": "irate(mysql_global_status_select_range_check{pod=\"$4ALLPORTAL_DB\"}[5m])",
     "legendFormat": "Select Range Check"
    },
    {
     "expr": "irate(mysql_global_status_select_scan{pod=\"$4ALLPORTAL_DB\"}[5m])",
     "legendFormat": "Select Scan"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  sum without(instance, node) (topk(1, (kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", persistentvolumeclaim=\"data-$4ALLPORTAL_DB\"})))\n  -\n  sum without(instance, node) (topk(1, (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", persistentvolumeclaim=\"data-$4ALLPORTAL_DB\"})))\n)\n",
     "legendFormat": "Used Space"
    },
    {
     "expr": "sum without(instance, node) (topk(1, (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", persistentvolumeclaim=\"data-$4ALLPORTAL_DB\"})))\n",
     "legendFormat": "Free Space"
    }
   ]
  }
 ]
}