{{ if .Values.users }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "common.names.fullname" . }}-user"
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
rules:
  - apiGroups:
      - ""
      - apps
      - autoscaling
      - batch
      - extensions
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/portforward
    verbs:
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "common.names.fullname" . }}-user"
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ include "common.names.fullname" . }}-user"
subjects:
  {{- range $name := .Values.users }}
  - kind: ServiceAccount
    name: {{ $name }}
    namespace: flux
      {{- end }}
  {{ end }}
