apiVersion: v2
description: A generic, base cluster setup
name: base-cluster
version: 37.0.2
home: "https://4allportal.com"
maintainers:
  - name: tasches
    email: s.tasche@4allportal.net
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.2.4
