{{- if and .Values.monitoring.securityScanning.enabled .Values.monitoring.prometheus.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: estafette
  namespace: security
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: estafette
spec:
  chart:
    spec:
      chart: estafette-vulnerability-scanner
      sourceRef:
        kind: HelmRepository
        name: estafette
        namespace: {{ .Release.Namespace }}
      version: 0.x.x
  interval: 1m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values:
    {{- if .Values.global.imageRegistry }}
    image:
      repository: "{{ $.Values.global.imageRegistry }}/estafette/estafette-vulnerability-scanner"
    {{- end }}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
    {{- if .Values.monitoring.prometheus.enabled }}
    serviceMonitor:
      enabled: true
    grafanaDashboard:
      enabled: true
  {{- end }}
  {{- end }}
