{{- if and .Values.monitoring.securityScanning.enabled .Values.monitoring.prometheus.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trivy
  namespace: security
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: trivy
spec:
  chart:
    spec:
      chart: trivy-operator
      sourceRef:
        kind: HelmRepository
        name: aqua
        namespace: {{ .Release.Namespace }}
      version: 0.x.x
  interval: 1m
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    {{- if .Values.global.imageRegistry }}
    registry: "{{ $.Values.global.imageRegistry }}"
    {{- end }}
    operator:
      scanJobsConcurrentLimit: 10
      scanNodeCollectorLimit: 1
    trivyOperator:
      scanJobTolerations: []
    trivy:
      ignoreUnfixed: true
      severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
      resources:
        requests:
          cpu: 100m
          memory: 100M
        limits:
          cpu: 500m
          memory: 500M
    {{- if .Values.monitoring.prometheus.enabled }}
    serviceMonitor:
      enabled: true
  {{- end }}
{{- end }}
