apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-cloudflare
  namespace: cert-manager
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: cert-manager
stringData:
  key: {{ required "You must provide the apiKey for Cloudflare" .Values.dns.apiKey }}
