apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: cert-manager
spec:
  acme:
    email: {{ required "You must provide the email for DNS" .Values.dns.email }}
    solvers:
      - dns01:
          {{- $_ := required "You must choose a DNS provider" .Values.dns.provider -}}
          {{- if (.Values.dns.provider).cloudflare }}
          cloudflare:
            email: {{ .Values.dns.email }}
            apiKeySecretRef:
              name: cert-manager-dns
              key: credentials
          {{- else if (.Values.dns.provider).aws }}
            {{- with .Values.dns.provider.aws }}
          route53:
            region: {{ .region | quote }}
            {{- end -}}
          {{- end -}}
        {{ with .Values.dns.domains }}
        selector:
          dnsZones:
      {{ . | toYaml | nindent 12 }}
      {{ end }}
      - http01:
          ingress: {}
    privateKeySecretRef:
      name: letsencrypt-prod-account
    server: https://acme-v02.api.letsencrypt.org/directory
