{{- if and .Values.webdav.enabled (eq (include "common.networkPolicy.type" . ) "cilium") }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: "{{ include "common.names.fullname" . }}-webdav"
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: webdav
spec:
  endpointSelector:
    matchLabels: {{- include "common.labels.matchLabels" $ | nindent 6 }}
      app.kubernetes.io/component: webdav
  ingress:
    - fromEndpoints:
        - matchLabels: {{- include "common.tplvalues.render" (dict "value" (include "common.dict.filterEmptyValues" .Values.global.networkPolicy.ingressLabels) "context" $) | nindent 12 }}
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
  egress:
    - { }
  {{- end }}
