{{- if and $.Values.webdav.enabled (eq .Values.webdav.secretName "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.secrets.name" (dict "existingSecret" (dict) "defaultNameSuffix" "webdav" "context" $) }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.stable" . | nindent 4 }}
type: Opaque
stringData:
  users: |
  {{- range $user, $password := .Values.webdav.users }}
    {{ $user }} {{ $password }}
  {{- end }}
  {{- end }}
