{{- if .Values.monitoring.ingress.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: ingress-monitor-operator
  namespace: monitoring
  labels: {{- omit (include "common.labels.standard" $ | fromYaml) "helm.sh/chart" | toYaml | nindent 4 }}
    app.kubernetes.io/component: ingress-monitoring
stringData:
  config.yaml: |- {{- omit .Values.monitoring.ingress "enabled" | toYaml | nindent 4 }}
    {{- end -}}
