apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  annotations:
    helm.sh/resource-policy: keep
  labels: {{- include "base-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingress
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
