{{- $helmRepositories := dict -}}
{{- $helmRepositories = set $helmRepositories "bitnami" "https://charts.bitnami.com/bitnami" -}}
{{- $helmRepositories = set $helmRepositories "descheduler" "https://kubernetes-sigs.github.io/descheduler" -}}
{{- if .Values.backup.enabled }}
  {{- $helmRepositories = set $helmRepositories "appscode" "https://charts.appscode.com/stable" -}}
{{- end }}
{{- $helmRepositories = set $helmRepositories "jetstack" "https://charts.jetstack.io" -}}
{{- $helmRepositories = set $helmRepositories "traefik" "https://helm.traefik.io/traefik" -}}
{{- $helmRepositories = set $helmRepositories "grafana" "https://grafana.github.io/helm-charts" -}}
{{- $helmRepositories = set $helmRepositories "aqua" "https://aquasecurity.github.io/helm-charts" -}}
{{- $helmRepositories = set $helmRepositories "stakater" "https://stakater.github.io/stakater-charts" -}}
{{- $helmRepositories = set $helmRepositories "prometheus" "https://prometheus-community.github.io/helm-charts" -}}
{{- $helmRepositories = set $helmRepositories "jaeger" "https://jaegertracing.github.io/helm-charts" -}}
{{- range $name, $url := $helmRepositories }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-namespace: {{ $.Release.Namespace }}
    meta.helm.sh/release-name: {{ $.Release.Name }}
spec:
  interval: 5m
  url: {{ $url }}
{{- end }}

