apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-setup
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
  annotations:
    helm.sh/hook-weight: "-1"
    helm.sh/hook: pre-install,pre-upgrade,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-setup
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
  annotations:
    helm.sh/hook-weight: "-1"
    helm.sh/hook: pre-install,pre-upgrade,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
  - nonResourceURLs:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-setup
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
  annotations:
    helm.sh/hook-weight: "-1"
    helm.sh/hook: pre-install,pre-upgrade,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: helm-setup
subjects:
  - kind: ServiceAccount
    name: helm-setup
    namespace: {{ .Release.Namespace }}
