{{- if .Values.global.imageCredentials -}}
  {{ range $name, $cred := .Values.global.imageCredentials -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $name }}"
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" (required "You must specify a registry host" $cred.host) (printf "%s:%s" (required "You must specify a registry username" $cred.username) (required "You must specify a registry password" $cred.password) | b64enc) | quote }}
---
{{- end }}
  {{- end -}}
