apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-website.fullname" . }}
  labels:
  {{- include "simple-website.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  {{- include "simple-website.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "simple-website.selectorLabels" . | nindent 8 }}
    {{- with .Values.deployment.additionalLabels }}
    {{- . | toYaml | nindent 8 }}
    {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.usePodSecurityContext }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- toYaml .Values.securityOptions | nindent 6 }}
      containers:
        - name: application
          {{- if .Values.useSecurityContext }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.env }}
          env:
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end -}}
          {{ end }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.healthPath }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.healthPath }}
              port: http
          resources:
      {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
  {{- toYaml . | nindent 8 }}
  {{- end }}
