apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-website.fullname" . }}
  labels:
    {{- include "simple-website.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "simple-website.selectorLabels" . | nindent 4 }}
