{{- if .Values.backup.enabled -}}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stash
  namespace: kube-system
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: stash
spec:
  chart:
    spec:
      chart: stash
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: {{ .Release.Namespace }}
      version: v2025.06.30
  interval: 1m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values:
    pushgateway:
      {{- if .Values.global.imageRegistry }}
      registry: "{{ $.Values.global.imageRegistry }}/prom"
    {{- end }}
    global:
      {{- if .Values.global.imageRegistry }}
      registry: "{{ $.Values.global.imageRegistry }}/stashed"
      {{- end }}
      licenseSecretName: {{ required "You need to provide a license secret for stash 😡" .Values.backup.licenseSecretName | quote }}
    features:
      community: true
    security:
      createPSPs:
        privileged: false
        baseline: false
    stash-community:
      criticalAddon: true
      enableAnalytics: false
      monitoring:
        agent: prometheus.io/operator
        backup: true
        operator: true
      apiserver:
        enableValidatingWebhook: false
        servingCerts:
          generate: true
---
{{ template "base-cluster.dashboards.configmap" (dict "folder" "backup" "context" .) }}
{{- end -}}
