{
 "title": "Galera/MariaDB - Overview",
 "description": "mariadb galera cluster overview. metrics from mysqld exporter.",
 "tags": [
  "mysql",
  "galera",
  "mariadb"
 ],
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(mysql_global_status_wsrep_cluster_size,service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Service Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mysql_up{service=~\"$cluster.*\"}"
    }
   ]
  },
  {
   "title": "Service Uptime",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "mysql_global_status_uptime{service=~\"$cluster.*\"}"
    }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_cluster_size{service=~\"$cluster.*\"}"
    }
   ]
  },
  {
   "title": "Cluster Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_cluster_status{service=~\"$cluster.*\"}"
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries{service=~\"$cluster.*\"}[1m])",
     "legendFormat": "{{ pod }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "Mysql Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{service=~\"$cluster.*\"}",
     "legendFormat": "Current - {{ pod }} ({{ instance }})"
    },
    {
     "expr": "mysql_global_variables_max_connections{service=~\"$cluster.*\"}",
     "legendFormat": "Max - {{ pod }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "mysql  disk reads vs writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_innodb_data_reads{service=~\"$cluster.*\"}[10m])",
     "legendFormat": "reads - {{ pod }} ({{ instance }})"
    },
    {
     "expr": "irate(mysql_global_status_innodb_data_writes{service=~\"$cluster.*\"}[10m])",
     "legendFormat": "write - {{ pod }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "mysql network received vs sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_bytes_received{service=~\"$cluster.*\"}[5m])",
     "legendFormat": "received - {{ pod }} ({{ instance }})"
    },
    {
     "expr": "irate(mysql_global_status_bytes_sent{service=~\"$cluster.*\"}[5m])",
     "legendFormat": "sent - {{ pod }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "Top Command Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(mysql_global_status_commands_total{service=~\"$cluster.*\"}[5m]))",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  },
  {
   "title": "MySQL File Openings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_opened_files{service=~\"$cluster.*\"}[1m])",
     "legendFormat": "{{ pod }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "MySQL Open Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_open_files{service=~\"$cluster.*\"}",
     "legendFormat": "Open Files - {{ pod }} ({{ instance }})"
    },
    {
     "expr": "mysql_global_variables_open_files_limit{service=~\"$cluster.*\"}",
     "legendFormat": "Open Files Limit - {{ pod }} ({{ instance }})"
    },
    {
     "expr": "mysql_global_status_innodb_num_open_files{service=~\"$cluster.*\"}",
     "legendFormat": "InnoDB Open Files - {{ pod }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "MySQL Slow Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_slow_queries{service=~\"$cluster.*\"}[1m])",
     "legendFormat": "Slow Queries on {{ pod }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "MySQL Aborted Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_aborted_connects{service=~\"$cluster.*\"}[1m])",
     "legendFormat": "Aborted Connects (attempts) on - {{ pod }} ({{ instance }})"
    },
    {
     "expr": "irate(mysql_global_status_aborted_clients{service=~\"$cluster.*\"}[1m])",
     "legendFormat": "Aborted Clients (timeout) on - {{ pod }} ({{ instance }})"
    }
   ]
  },
  {
   "title": "Galera Replicated Bytes / Hour",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 48, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(mysql_global_status_wsrep_replicated_bytes{service=~\"$cluster.*\"}[1h])",
     "legendFormat": "{{ pod }} ({{ instance }})"
    }
   ]
  }
 ]
}