{{- if and false .Release.IsUpgrade }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}-upgrade
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
  annotations: 
    helm.sh/hook: pre-upgrade,pre-rollback
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "common.names.fullname" . }}-upgrade
      containers:
        - name: update-crds
            {{- if $.Values.kubectl.image.registry }}
          registry: {{ $.Values.kubectl.image.registry }}
          image: {{ $.Values.kubectl.image.repository }}: {{ $.Values.kubectl.image.tag }}
            {{- else }}
          image: "bitnami/kubectl"
            {{- end }}
          args:
            - -n
            - {{ .Release.Namespace }}
            - apply
            - --server-side
            - -f
            - {{ .Files.Get "./crds/prometheus-operator.yaml" }}
{{- end }}
