{{- if .Values.monitoring.metricsServer.enabled -}}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: monitoring
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: metrics-server
spec:
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: {{ .Release.Namespace }}
      version: 6.x.x
  interval: 1m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values:
    {{- if .Values.global.imageRegistry }}
    global:
      imageRegistry: {{ $.Values.global.imageRegistry | quote }}
    {{- end }}
    resources:
      limits:
        cpu: {{ .Values.monitoring.metricsServer.resources.limits.cpu }}
        memory: {{ .Values.monitoring.metricsServer.resources.limits.memory }}
    priorityClassName: system-cluster-critical
    extraArgs:
      kubelet-preferred-address-types: InternalIP
      kubelet-insecure-tls: "true"
    apiService:
      create: true
  {{- end -}}
