{{- if or .Values.monitoring.jaeger.enabled .Values.monitoring.metricsServer.enabled .Values.monitoring.prometheus.enabled .Values.monitoring.ingress.enabled .Values.monitoring.goldpinger.enabled .Values.monitoring.deadMansSwitch.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    helm.sh/resource-policy: keep
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: monitoring
  {{- end }}
