apiVersion: v2
name: maxscale
description: Deploys a maxscale mariadb-galera proxy including mariadb-galera
type: application
version: 3.2.8
appVersion: 6.4.1
maintainers:
  - name: tasches
    email: s.tasche@4allportal.com

dependencies:
  - name: common
    repository: https://charts.bitnami.com
    version: 1.16.1
  - repository: https://charts.bitnami.com
    name: mariadb-galera
    version: 7.3.7
    alias: mariadb
