apiVersion: v2
name: maxscale
description: Deploys a maxscale mariadb-galera proxy including mariadb-galera
type: application
version: 4.1.14
appVersion: 23.02.2
maintainers:
  - name: jpkraemer-mg
    email: j.kraemer@4allportal.com

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.19.3
  - repository: https://charts.bitnami.com/bitnami
    name: mariadb-galera
    version: 14.2.6
    alias: mariadb
