name: Lint Code Base

"on":
  - pull_request

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    env:
      CT_TARGET_BRANCH: ${{ github.event.repository.default_branch }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.18.6

      - name: install yq
        run: |
          sudo snap install yq

      - name: Extract helm repos
        id: helm-repos
        run: |
          echo -n "::set-output name=repos::"
          for DIR in ./charts/*; do
            FILE="$DIR/Chart.yaml"
            DIR="${DIR//\./}"
            yq e '.dependencies.[].repository' "$FILE"
          done | sort -u | awk '{printf (NR>1 ? "," : "") NR "=" $1}'
          echo

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Lint charts
        run: ct lint
        env:
          CT_CHART_REPOS: ${{ steps.helm-repos.outputs.repos }}
