name: Lint Code Base

# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

"on":
  pull_request:
    paths:
      - charts/*

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    env:
      CT_TARGET_BRANCH: ${{ github.event.repository.default_branch }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Lint charts
        run: ct lint
