name: Sync CODEOWNERS

"on": workflow_call

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install yq
        run: |
          sudo snap install yq
      - name: generate CODEOWNERS
        run: |
          ./.github/scripts/sync-codeowners.sh > .github/CODEOWNERS
      - name: commit CODEOWNERS modifications
        run: |
          if ! git diff --exit-code; then
            git config user.name "$GITHUB_ACTOR"
            git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git add . && git commit -am "Update 'CODEOWNERS'" && git push
          fi
