apiVersion: v1
kind: Namespace
metadata:
  name: reflector
  labels: {{- include "base-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: reflector
    pod-security.kubernetes.io/enforce: baseline
